INSERT INTO restaurants (name, address, rating, price_range, open_time, close_time, type) VALUES 
('Dimsum Mr Hào', '171A Nguyễn Văn Cừ, Quận 5', 4.3, 150000, '08:00', '22:00', 'chinese'),
('Mì Cay Naga', '213F Nguyễn Văn Cừ, Quận 5', 4.0, 60000, '09:00', '22:30', 'korean'),
('Texas Chicken', '217B Nguyễn Văn Cừ, Quận 5', 4.2, 100000, '09:00', '21:00', 'fastfood'),
('Phở Lệ', '413-415 Nguyễn Trãi, Quận 5', 4.6, 85000, '06:00', '01:00', 'vietnamese'),
('The Alley', '151 Nguyễn Văn Cừ, Quận 5', 4.4, 65000, '09:00', '22:00', 'cafe');

-- D. Nạp Menu cho từng quán (mỗi quán 3 món)--
-- Quán 1: Dimsum Mr Hào--
INSERT INTO menu_items (restaurant_id, name, description, price, food_type, ingredients) VALUES 
(1, 'Há Cảo Tôm Tươi', 'Há cảo vỏ mỏng nhân tôm giòn', 45000, 'chinese', 'shrimp,flour'),
(1, 'Xíu Mại Trứng Muối', 'Xíu mại thịt heo kèm trứng muối', 45000, 'chinese', 'pork,salted egg'),
(1, 'Bánh Bao Kim Sa', 'Nhân trứng muối tan chảy', 40000, 'dessert', 'flour,egg,milk');

-- Quán 2: Mì Cay Naga--
INSERT INTO menu_items (restaurant_id, name, description, price, food_type, ingredients) VALUES 
(2, 'Mì Cay Hải Sản', 'Mì cay cấp độ 1-7', 55000, 'korean', 'noodle,shrimp,squid'),
(2, 'Mì Cay Bò', 'Mì cay với thịt bò mềm', 50000, 'korean', 'noodle,beef'),
(2, 'Takoyaki', 'Bánh bạch tuộc nướng', 35000, 'appetizer', 'flour,octopus');

-- Quán 3: Texas Chicken--
INSERT INTO menu_items (restaurant_id, name, description, price, food_type, ingredients) VALUES 
(3, 'Gà Rán Cay (2 miếng)', 'Gà rán giòn rụm tẩm vị', 75000, 'fastfood', 'chicken,flour'),
(3, 'Bánh Quy Mật Ong', 'Bánh nướng bơ mật ong', 15000, 'fastfood', 'flour,honey'),
(3, 'Khoai Tây Chiên', 'Khoai tây vàng giòn', 25000, 'fastfood', 'potato');

-- Quán 4: Phở Lệ--
INSERT INTO menu_items (restaurant_id, name, description, price, food_type, ingredients) VALUES 
(4, 'Phở Tái Nạm', 'Thịt tái và nạm gầu thơm ngon', 75000, 'vietnamese', 'beef,rice noodle'),
(4, 'Phở Bò Viên', 'Nước dùng trong, bò viên dai', 70000, 'vietnamese', 'beef,rice noodle'),
(4, 'Trà Đá', 'Giải khát', 5000, 'drink', 'tea');

-- Quán 5: The Alley--
INSERT INTO menu_items (restaurant_id, name, description, price, food_type, ingredients) VALUES 
(5, 'Sữa Tươi Trân Châu Đường Đen', 'Best seller của quán', 65000, 'cafe', 'milk,boba,sugar'),
(5, 'Trà Sữa Lài', 'Hương lài thơm mát', 50000, 'cafe', 'jasmine tea,milk'),
(5, 'Trà Đào Đào', 'Trà xanh giải nhiệt kèm đào miếng', 55000, 'cafe', 'green tea,peach');

-- QUẬN 6
INSERT INTO restaurants (name, address, rating, price_range, open_time, close_time, type) VALUES 
('Mì Trộn, Bánh Tráng Trộn & Cuốn Trứng Cút Lòng Đào - Ăn Vặt Quận 6', '444/1 Phạm Văn Chí, P. 8, Quận 6, TP. HCM', 4.5, 40000, '08:00', '22:00', 'snack'),
('Ăn Vặt Cá Viên Chiên Phát Lộc 9999 - Quận 6', '511A/1 Đường Hậu Giang, P. 11, Quận 6, TP. HCM', 5.0, 50000, '08:00', '22:00', 'snack'),
('Cơm Tấm 279', '279 Hậu Giang, P. 5, Quận 6, TP. HCM', 4.5, 45000, '06:00', '21:00', 'vietnamese'),
('Mến - Bún Chả Cá Sứa Nha Trang - Hậu Giang', '208 Hậu Giang, P. 9, Quận 6, TP. HCM', 4.5, 70000, '07:00', '22:00', 'vietnamese'),
('Cơm Tấm 3 Chị Em', '733 Lò Gốm, P. 9, Quận 6, TP. HCM', 4.5, 55000, '06:00', '22:00', 'vietnamese'),
('Mì Trộn & Xiên Que Cá Con - Đồ Ăn Vặt - Quận 6', '151 Bãi Sậy, P. 1, Quận 6, TP. HCM', 0.0, 50000, '08:00', '22:00', 'snack'),
('Bánh Cuốn & Bánh Ướt Phú Lâm', '1/1A Tân Hòa Đông, P. 13, Quận 6, TP. HCM', 4.5, 40000, '06:00', '21:00', 'vietnamese'),
('Phở Thắng - Phở Bò - Quận 6', '224 Minh Phụng, P. 6, Quận 6, TP. HCM', 4.5, 65000, '06:00', '22:00', 'vietnamese'),
('Ốc Trứng Muối - Chi Nhánh Quận 6', '188A Mai Xuân Thưởng, P. 2, Quận 6, TP. HCM', 3.5, 80000, '15:00', '23:00', 'seafood'),
('Neko Izakaya Bar Nhậu Kiểu Nhật - Quận 6', '291 Bình Tiên, P. 8, Quận 6, TP. HCM', 4.5, 150000, '16:00', '02:00', 'japanese'),
('Ăn Vặt 3 Chị Em - Quận 6', '240/88 Nguyễn Văn Luông, P. 11, Quận 6, TP. HCM', 4.5, 60000, '08:00', '22:00', 'snack'),
('Cháo Ếch Singapore Geylang SD88 - Quận 6', 'D40 Cư Xá Phú Lâm B, P. 13, Quận 6, TP. HCM', 4.5, 80000, '09:00', '23:00', 'singapore'),
('Cà Ri Vịt - Bạc Liêu - Quận 6', '496/34 Hậu Giang, Quận 6, TP. HCM', 0.0, 85000, '08:00', '22:00', 'vietnamese'),
('Gà Rán Và Mì Ý - Jollibee EC Hậu Giang Quận 6', '704 Đường Hậu Giang, P. 12, Quận 6, TP. HCM', 4.5, 60000, '09:00', '22:00', 'fastfood'),
('Thắng Lợi Mì Gia - Mì Vịt Tiềm & Dimsum - Quận 6', '213 Nguyễn Văn Luông, P. 11, Quận 6, TP. HCM', 4.5, 100000, '07:00', '22:00', 'chinese'),
('SOI THAI - MÓN THÁI, TRÀ SỮA QUẬN 6', '79 Kinh Dương Vương, P. 12, Quận 6, TP. HCM', 4.5, 150000, '09:00', '22:00', 'thai'),
('Xôi Ghẹ 192 Quận 6 - Phạm Văn Chí', '200 Phạm Văn Chí, P. 4, Quận 6, TP. HCM', 4.5, 80000, '06:00', '22:00', 'vietnamese'),
('Cô Điệp - Nem Nướng Nha Trang - Quận 6', 'D36 Cư Xá Phú Lâm B, P. 13, Quận 6, TP. HCM', 4.5, 70000, '09:00', '22:00', 'vietnamese'),
('Cơm Gà Hải Nam Tam Kỳ 142 - Cháo, Gỏi & Miến Gà Trộn - 34 Bình Phú, Quận 6', '34 Bình Phú, P. 11, Quận 6, TP. HCM', 4.5, 75000, '07:00', '22:00', 'vietnamese');

-- QUẬN 5
INSERT INTO restaurants (name, address, rating, price_range, open_time, close_time, type) VALUES 
('Cơm Tấm Sườn Nướng, Trà Sữa & Ăn Vặt Quận 5 - Phùng Hưng', '89/12 Phùng Hưng, P. 13, Quận 5, TP. HCM', 4.0, 45000, '06:00', '22:00', 'vietnamese'),
('Lẩu Bò Hân Quận 5 - Nguyễn Biểu', '88 Nguyễn Biểu, P. 1, Quận 5, TP. HCM', 4.5, 150000, '10:00', '23:00', 'hotpot'),
('Bánh Kem & Bánh Ngọt - 1819 Gato Quận 5', '813 Trần Hưng Đạo, P. 1, Quận 5, TP. HCM', 3.5, 60000, '08:00', '22:00', 'bakery'),
('Bánh Sầu Riêng 9 Sạch - Quận 5', 'Số 04B Chung Cư 109 Nguyễn Biểu, P. 1, Quận 5, TP. HCM', 4.5, 175000, '09:00', '22:00', 'bakery'),
('Ốc Trứng Muối - Chi Nhánh 5 Quận 5', '55 Nguyễn Chí Thanh, P. 9, Quận 5, TP. HCM', 4.5, 80000, '15:00', '23:30', 'seafood'),
('Domoto Saigon Quận 5 - Quán Cơm Nhật Bình Dân - Trần Hưng Đạo', '835/32 Trần Hưng Đạo, P. 1, Quận 5, TP. HCM', 4.5, 100000, '10:30', '22:00', 'japanese'),
('Ốc Trứng Muối - Chi Nhánh Quận 5', '244 Đường Trần Phú, P. 9, Quận 5, TP. HCM', 0.0, 80000, '15:00', '23:30', 'seafood'),
('Truyền Thuyết Champong - Nguyễn Trãi Quận 5', '197 Nguyễn Trãi, P. 2, Quận 5, TP. HCM', 4.5, 180000, '10:00', '22:00', 'korean'),
('An Lạc - Ăn Chay - Quận 5', '129/17 Nguyễn Trãi, P. 2, Quận 5, TP. HCM', 4.5, 30000, '07:00', '21:00', 'vegetarian'),
('Tàu Hũ Tươi Covang Quận 5 - Trần Tuấn Khải', '159 Trần Tuấn Khải, P. 5, Quận 5, TP. HCM', 5.0, 30000, '08:00', '22:00', 'dessert');

-- QUẬN 10
INSERT INTO restaurants (name, address, rating, price_range, open_time, close_time, type) VALUES 
('Nem Nướng Nha Trang - Since 1982 - Quận 10', '451/29/26 Tô Hiến Thành, P. 14, Quận 10, TP. HCM', 3.5, 45000, '08:00', '22:00', 'vietnamese'),
('Bo Food - Gà Quay, Sườn Quay & Cơm Lam Bánh Bao Quận 10 - Bà Hạt', 'Số 484 Bà Hạt, P. 8, Quận 10, TP. HCM', 4.5, 250000, '09:00', '22:00', 'vietnamese'),
('CHÂN GÀ GOOD - QUẬN 10', '63-65 Ngô Quyền, P. 6, Quận 10, TP. HCM', 4.5, 90000, '10:00', '23:00', 'snack'),
('Mì Trộn Phủ Trứng - Quận 10', '104/42 Thành Thái, P. 14, Quận 10, TP. HCM', 4.5, 69000, '08:00', '22:00', 'noodle'),
('Gà Rán YumIco - Quận 10', '031 Lô U Chung Cư Ngô Gia Tự, P. 12, Quận 10, TP. HCM', 4.5, 80000, '09:00', '22:00', 'fastfood'),
('Bánh Tráng Muối Tỏi & Dừa Tắc Quận 10 - Hòa Hưng', '83/14E Hòa Hưng, P. 12, Quận 10, TP. HCM', 4.5, 25000, '08:00', '22:00', 'beverage'),
('Ốc Trứng Muối - Chi Nhánh 4 Quận 10', 'G1A Trường Sơn, P. 15, Quận 10, TP. HCM', 4.0, 80000, '15:00', '23:30', 'seafood'),
('Chiang Thai Delivery - Quận 10', '104/59 Thành Thái, P. 12, Quận 10, TP. HCM', 4.5, 75000, '10:00', '22:00', 'thai'),
('Truyền Thuyết Champong - Quận 10', 'CC8 - CC9 - CC10 Trường Sơn, P. 15, Quận 10, TP. HCM', 4.5, 140000, '10:00', '22:00', 'korean'),
('Bò Né 3 Anh Em Quận 10', '013-014 Lô K Chung Cư Ngô Gia Tự, Đường Sư Vạn Hạnh, P. 2, Quận 10, TP. HCM', 4.5, 75000, '06:00', '22:00', 'vietnamese');

-- QUẬN 11
INSERT INTO restaurants (name, address, rating, price_range, open_time, close_time, type) VALUES 
('Kênh Bà Châu - Cá Hồi Ngâm Tương Thạng Hạng', '6/8C Tân Hoá, P. 1, Quận 11, TP. HCM', 4.5, 150000, '10:00', '21:00', 'japanese'),
('Phở Trường Sơn - Quận 11', '273 Lạc Long Quân, P. 3, Quận 11, TP. HCM', 4.5, 60000, '06:00', '22:00', 'vietnamese'),
('Bánh Mì Tuấn Mập - Bánh Mì Chảo & Bò Bít Tết - Lãnh Binh Thăng', '116 Lãnh Binh Thăng, Quận 11, TP. HCM', 4.5, 55000, '06:00', '21:00', 'vietnamese'),
('Cơm Bò Beefsteak Phủ Trứng 24H - Bình Thới', '25 Đường Số 6, P. 8, Quận 11, TP. HCM', 4.5, 65000, '00:00', '23:59', 'vietnamese'),
('Hủ Tiếu Chay - Tôn Thất Hiệp', '11A Tôn Thất Hiệp, P. 13, Quận 11, TP. HCM', 4.5, 35000, '07:00', '20:00', 'vegetarian'),
('Cơm Truyền Ký - Quận 11', '39/20 Lý Thường Kiệt, Quận 11, TP. HCM', 4.5, 100000, '10:00', '21:00', 'chinese'),
('Sủi Cảo Ngọc Ý - Hà Tôn Quyền', '187 - 189 Hà Tôn Quyền, P. 7, Quận 11, TP. HCM', 4.5, 70000, '11:00', '23:00', 'chinese'),
('Sủi Cảo Thiên Thiên - Hà Tôn Quyền', '195 Hà Tôn Quyền, P. 4, Quận 11, TP. HCM', 4.5, 70000, '13:00', '23:30', 'chinese'),
('Sủi Cảo 193 - Hà Tôn Quyền', '193 Hà Tôn Quyền, P. 4, Quận 11, TP. HCM', 4.5, 70000, '11:00', '23:00', 'chinese'),
('Sủi Cảo 162 - Hà Tôn Quyền', '162 Hà Tôn Quyền, P. 4, Quận 11, TP. HCM', 4.5, 70000, '11:00', '23:00', 'chinese'),
('Bò Né 3 Anh Em - Quận 11', '221 Hòa Bình, P. Hiệp Tân, Quận 11, TP. HCM', 4.5, 75000, '07:00', '22:00', 'vietnamese'),
('Tàu Hũ tươi Covang Quận 11 - Bình Thới', '166 Bình Thới, P. 14, Quận 11, TP. HCM', 5.0, 30000, '08:00', '22:00', 'dessert'),
('Bánh Cuốn & Bánh Ướt Phú Lâm - Quận 11', '221/11 Lãnh Binh Thăng, P. 12, Quận 11, TP. HCM', 4.5, 40000, '06:00', '21:00', 'vietnamese'),
('Bánh Sầu Riêng 9 Sạch - Quận 11', '138 Lạc Long Quân, P. 10, Quận 11, TP. HCM', 4.5, 175000, '09:00', '21:00', 'bakery'),
('Ăn Vặt 3 Chị Em - Quận 11', '110/33/2 Ông Ích Khiêm, P. 5, Quận 11, TP. HCM', 4.5, 60000, '09:00', '22:00', 'snack'),
('SOI THAI - MÓN THÁI, TRÀ SỮA QUẬN 11', '120 Bình Thới, P. 14, Quận 11, TP. HCM', 4.5, 120000, '10:00', '22:00', 'thai'),
('Mì Trộn & Xiên Que Cá Con - Quận 11', '45 Đường Số 2, Cư Xá Bình Thới, Quận 11, TP. HCM', 4.0, 50000, '08:00', '21:00', 'snack'),
('Gà Rán YumIco - Quận 11', '25 Đường Số 16, Cư Xá Lữ Gia, Quận 11, TP. HCM', 4.5, 80000, '09:00', '22:00', 'fastfood'),
('Mì Trộn Phủ Trứng - Quận 11', '341/14D Lạc Long Quân, P. 5, Quận 11, TP. HCM', 4.5, 65000, '08:00', '21:00', 'noodle'),
('An Lạc - Ăn Chay - Quận 11', '221/11 Lãnh Binh Thăng, P. 12, Quận 11, TP. HCM', 4.5, 30000, '07:00', '21:00', 'vegetarian');

-- NẠP MENU ITEM TỪNG QUẬN --
INSERT INTO menu_items (restaurant_id, name, description, price, food_type, ingredients) VALUES 
-- MENU QUẬN 6 (ID 6 ĐẾN 24)
(6, 'Bánh tráng phơi sương dẻo Trộn MỠ HÀNH satế', 'Bánh tráng, muối, satế, mỡ hành, tắc, rau răm', 26000, 'snack', 'rice paper,quail egg,scallion,chili'),
(6, 'Bánh Tráng Phơi Sương Trộn Mỡ Hành Trứng Cút', '', 35000, 'snack', 'rice paper,quail egg,pork fat,scallion'),
(6, 'Bánh tráng phơi sương dẻo trộn satế TỎI PHI', 'Bánh tráng,muối, satế, tỏi phi,rau răm,tắc', 26000, 'snack', 'rice paper,garlic,quail egg,chili'),
(6, 'Bánh Tráng Phơi Sương Dẻo Trộn MỠ HÀNH Thập Cẩm', 'Bánh tráng phơi sương dẻo, 3 trứng cút lòng đào', 50000, 'snack', 'rice paper,beef jerky,dried squid,quail egg'),
(6, 'Bánh Tráng Phơi Sương Trộn Mỡ Hành Khô Bò Giòn', '', 38000, 'snack', 'rice paper,quail egg,beef jerky,scallion'),
(7, 'Mì Trộn Indomie Thập Cẩm', 'Mì Trộn + 8 viên chiên thập cẩm, rau xanh', 45000, 'snack', 'noodle,fish ball,vegetable'),
(7, 'Mì Trộn Indomie_ 2 xúc xích', 'Mì trộn+ 2 cây xúc xích,rau xanh hành phi mở hành', 45000, 'snack', 'noodle,sausage,vegetable'),
(7, 'Mì Trộn Indomie 1 cây Xúc Xích chiên ( 2gói )', 'Mì Indomie ( 2 gói ), 1 cây xúc xích Đức', 43000, 'snack', 'noodle,sausage,vegetable'),
(7, 'Mì trộn Indomie + 2Trứng ốp la', 'Mì Trộn + 2 trứng ốp la, rau xanh', 35000, 'snack', 'noodle,egg,vegetable'),
(7, 'Mì Trộn Indomie Thập cẩm đặt biệt', 'Mì Trộn, 3 cá viên, 3bò viên,3 viên tôm, 1 xúc xích', 56000, 'snack', 'noodle,fish ball,beef ball,sausage,egg'),
(8, 'Cơm Mắm Chưng', '', 30000, 'vietnamese', 'rice,fermented fish,pork,egg'),
(8, 'Cơm Khổ Qua Cà Chớn', '', 30000, 'vietnamese', 'rice,bitter melon,pork'),
(8, 'Cơm Bì Ốp La', '', 30000, 'vietnamese', 'rice,shredded pork skin,egg'),
(8, 'Cơm Tấm Bì', '', 30000, 'vietnamese', 'rice,shredded pork skin'),
(8, 'Cơm Sườn', 'Hotline 0931377317', 50000, 'vietnamese', 'rice,pork chop,fish sauce'),
(9, 'Bún Đầy Đủ', 'Gồm chả +cá+ sứa + sườn non', 70000, 'vietnamese', 'noodle,fish cake,jellyfish,pork rib'),
(9, 'Bún Bình Thường', '( Chả + Cá )', 60000, 'vietnamese', 'noodle,fish cake,fish'),
(9, 'Combo Bún Đầy Đủ (Chả + Sứa + Cá + Sườn Non)', '', 85000, 'vietnamese', 'noodle,fish cake,jellyfish,pork rib,beverage'),
(9, 'Combo Bún Đầy Đủ (Có cả thế giới) + Sting', '', 85000, 'vietnamese', 'noodle,fish cake,jellyfish,pork rib,beverage'),
(9, 'Combo Bún Chả + Cá + Pepsi', '', 70000, 'vietnamese', 'noodle,fish cake,fish,beverage'),
(10, 'Cơm Tấm Sườn', 'Tất cả các món ăn đều được tặng canh ạ', 45000, 'vietnamese', 'rice,pork chop,fish sauce'),
(10, 'Cơm tấm sườn chả', 'Giá đã bao gồm hộp', 55000, 'vietnamese', 'rice,pork chop,egg meatloaf'),
(10, 'Cơm tấm sườn ốp la', 'Giá đã bao gồm hộp', 55000, 'vietnamese', 'rice,pork chop,egg'),
(10, 'Cơm Tấm sườn bì chả', 'Giá đã bao gồm hộp', 65000, 'vietnamese', 'rice,pork chop,shredded pork skin,egg meatloaf'),
(10, 'Cơm Tấm Sườn Chả Ốp La', 'Giá đã bao gồm hộp', 65000, 'vietnamese', 'rice,pork chop,egg meatloaf,egg'),
(11, 'COMBO Ngẫu Nhiên 1', '', 100000, 'snack', 'noodle,fish ball,sausage'),
(11, 'COMBO NO NÊ', '1 Mì Trộn Cá Viên + 1 Nước Uống', 50000, 'snack', 'noodle,fish ball,beverage'),
(11, 'COMBO TIẾT KIỆM 2', 'Ngẫu nhiên 5 loại topping + 1 nước uống', 50000, 'snack', 'noodle,mixed topping,beverage'),
(11, 'COMBO Ngẫu Nhiên 2', '', 150000, 'snack', 'noodle,fish ball,beef ball,sausage'),
(11, 'COMBO TIẾT KIỆM 1', 'Ngẫu nhiên 3 loại topping + 1 nước uống', 40000, 'snack', 'noodle,mixed topping,beverage'),
(12, '1 bánh ướt đặc biệt đầy đủ + 1 7up', 'Nước có thể chọn: Pepsi/Oolong Tea/Sting', 65000, 'vietnamese', 'rice noodle,pork sausage,beverage'),
(12, '7Up', '', 15000, 'vietnamese', 'beverage'),
(12, '1 Bánh cuốn trứng lá dứa đầy đủ + 1 7up', 'Nước có thể chọn: Pepsi/Oolong Tea', 65000, 'vietnamese', 'rice noodle,egg,pandan,beverage'),
(12, '1 Bánh cuốn trứng hoa đậu biết đầy đủ', 'Nước có thể chọn: Pepsi/Oolong Tea', 65000, 'vietnamese', 'rice noodle,egg,butterfly pea,beverage'),
(12, 'Bánh dày kẹp chả chiên chả lụa', '', 20000, 'vietnamese', 'sticky rice,pork sausage'),
(13, 'Phở Đặc Biệt', 'Tái + nạm + gân + viên', 72000, 'vietnamese', 'rice noodle,beef,beef tendon,beef ball'),
(13, 'Phở Tái', 'Phothang.com', 62000, 'vietnamese', 'rice noodle,rare beef'),
(13, 'Phở Tái Viên', 'Phothang.vn', 62000, 'vietnamese', 'rice noodle,rare beef,beef ball'),
(13, 'Phở Thập cẩm', 'Tái + gân + viên', 62000, 'vietnamese', 'rice noodle,beef,beef tendon,beef ball'),
(13, 'Phở Tái Nạm', 'Phothang.vn', 62000, 'vietnamese', 'rice noodle,rare beef,beef flank'),
(14, 'Trứng gà non sốt mắm tắc', '', 89000, 'seafood', 'young chicken egg,kumquat,fish sauce'),
(14, 'Trứng gà non cháy tỏi tóp mỡ', '', 89000, 'seafood', 'young chicken egg,garlic,pork fat'),
(14, 'Trứng gà non xào rau muống', '', 89000, 'seafood', 'young chicken egg,water spinach,garlic'),
(14, 'Răng mực cháy tỏi tóp mỡ', '', 79000, 'seafood', 'squid teeth,garlic,pork fat'),
(14, 'Răng mực sốt tiêu đen', '', 79000, 'seafood', 'squid teeth,black pepper'),
(15, 'Hành paro nướng', 'Xiên nướng lúc order sẽ đợi nướng hơi lâu', 12273, 'japanese', 'leek,sauce'),
(15, 'Cua cà mau sốt phô mai Neko', 'Thịt cua nướnh cùng sốt phô mai nấm', 133650, 'japanese', 'crab,cheese,mushroom'),
(15, 'Cá Mắt Kính', 'Nướng muôid hoặc muối ớt', 79200, 'japanese', 'fish,salt,chili'),
(15, 'Cá bò da sizeM nướng muối / muối ớt', 'Giá sẽ có thay đổi thep mùa', 323400, 'japanese', 'leatherjacket fish,salt,chili'),
(15, 'Cá Bò size S nướng muối / muối ớt', 'Giá có thể thay đổi theo mùa', 257400, 'japanese', 'leatherjacket fish,salt,chili'),
(16, 'Chân Gà Chiên Rút Xương', 'Chân gà (rau răm, dưa leo, cải chua, muối ớt xanh)', 90000, 'snack', 'chicken feet,cucumber,chili salt'),
(16, 'Khoai Tây Lắc Phô Mai', '', 38000, 'snack', 'potato,cheese'),
(16, 'Mẹt Chiên Cá Viên (size S)', 'Cá Viên, Tôm Viên, Bò Viên, Xúc Xích', 53000, 'snack', 'fish ball,beef ball,shrimp ball,sausage'),
(16, 'Mẹt Chiên Cá Viên (size M)', 'Đậu hủ phô mai, Bánh bao cá hồi, Sò điệp vàng', 90000, 'snack', 'fish ball,beef ball,cheese tofu,sausage'),
(16, 'Gà Viên Lắc Phô Mai', '', 38000, 'snack', 'chicken,cheese,flour'),
(17, 'Kho quẹt + rau củ + bánh mì', '', 72000, 'singapore', 'caramelized fish sauce,pork fat,vegetable,bread'),
(17, 'Kho quẹt + rau củ phần nhỏ', '', 49500, 'singapore', 'caramelized fish sauce,pork fat,vegetable'),
(17, '1 trứng Muối', '', 13500, 'singapore', 'salted egg'),
(17, 'Cháo Trắng Trứng Muối 2 trứng', '', 35100, 'singapore', 'porridge,salted egg'),
(17, 'Ếch ú nu 2 con + 1 cháo nóng hổi', 'ếch ú nu kho sốt singapore ngon bá cháy', 116100, 'singapore', 'frog,porridge,singapore sauce'),
(18, 'Cà ri vịt Bạc Liêu-Đùi+cánh', 'Hủ tiếu, đùi vịt, cánh vịt, nước sốt đậm đà', 89000, 'vietnamese', 'noodle,duck leg,duck wing,curry'),
(18, 'Cà ri vịt Bạc Liêu-Đùi+thịt', 'Hủ tiếu, đùi vịt, thịt vịt, nước sốt đậm đà', 89000, 'vietnamese', 'noodle,duck leg,duck meat,curry'),
(18, 'Cà ri vịt Bạc Liêu-Thịt', 'Hủ tiếu, thịt nạt mềm, nước sốt đậm đà', 79000, 'vietnamese', 'noodle,duck meat,curry'),
(18, 'Cà ri vịt Bạc Liêu-Đùi+gan', 'Hủ tiếu, đùi vịt, gan vịt, nước sốt đậm đà', 89000, 'vietnamese', 'noodle,duck leg,duck liver,curry'),
(18, 'Cà ri vịt Bạc Liêu-Đùi', 'Hủ tiếu, đùi vịt, nước sốt đậm đà', 89000, 'vietnamese', 'noodle,duck leg,curry'),
(19, '1 Mì ý sốt cay vừa + 1 miếng Gà', '1 Mì ý sốt cay vừa + 1 miếng Gà Giòn', 78000, 'fastfood', 'spaghetti,fried chicken,beverage'),
(19, 'Mỳ Ý sốt cay vừa + 1 Pepsi vừa', 'Food', 45000, 'fastfood', 'spaghetti,beverage'),
(19, 'Mỳ Ý sốt cay vừa', 'Food', 40000, 'fastfood', 'spaghetti,tomato sauce'),
(19, 'Mỳ Ý sốt cay lớn', 'Food', 50000, 'fastfood', 'spaghetti,tomato sauce'),
(19, 'Trà chanh hạt chia', '1 Trà chanh hạt chia [MỚI]', 20000, 'beverage', 'tea,lemon,chia seed'),
(20, 'Bánh bao xá xíu', '2 cái', 62667, 'chinese', 'flour,bbq pork'),
(20, 'Mì vịt tiềm 1/4', '2 vắt+1/4 vit tiềm', 136000, 'chinese', 'egg noodle,duck,herb broth'),
(20, 'Mì vịt tiềm thịt', '2 vắt mì + thit vit Tiềm', 99000, 'chinese', 'egg noodle,duck,herb broth'),
(20, 'Mì hoành thánh xá xíu', '2 vắt mì+ xá xíu', 99000, 'chinese', 'egg noodle,wonton,bbq pork'),
(20, 'Mì thập cẩm', '2 vắt mì + tôm + xá xíu + cá vien + mực khô', 99000, 'chinese', 'egg noodle,shrimp,bbq pork,fish ball'),
(21, 'Combo Gác Lại Âu Lo', 'Mua 3 Được 4 - Pad Thái Bò - Xôi Xiên Ba Rọi', 220000, 'thai', 'pad thai,beef,sticky rice,pork,milk tea'),
(21, 'Combo Thịnh Vượng', '- Pad Thái Tôm - Xôi Xiêm Ba Rọi Thái', 198000, 'thai', 'pad thai,shrimp,sticky rice,pork'),
(21, 'Combo Mai An Tiêm', '- Cơm Chiên Cua Thái - Xôi Xoài Thái', 195000, 'thai', 'fried rice,crab,sticky rice,mango,milk tea'),
(21, 'Combo Hương Lộc', 'Mua 2 Được 3 - Cơm chiên cua - Chè Thái', 143000, 'thai', 'fried rice,crab,thai sweet soup,tea'),
(21, 'Combo Ngày Mới', '- Tomyum Thái - Gỏi Miến Hải Sản', 189000, 'thai', 'tomyum,shrimp,glass noodle,seafood'),
(22, 'Combo Xôi Ghẹ đặc biệt', 'Topping : ghe + cha bong , hanh phi , rong bien', 125000, 'vietnamese', 'sticky rice,crab,pork floss,cheese'),
(22, 'Combo Xôi Ghẹ - Hải Sản + Mai Cua', 'Topping: Hải sản tươi ngon, ghẹ, tôm, mực', 145000, 'vietnamese', 'sticky rice,crab,shrimp,squid,cheese'),
(22, 'Xôi Ghẹ - Hải Sản Vỏ Giòn', 'Topping Ghẹ, Cá Cơm Rim, Tôm, Mực, Rong Biển', 75000, 'vietnamese', 'sticky rice,crab,shrimp,squid,pork floss'),
(22, 'Xôi Ghẹ - Hải Sản Vỏ Giòn Đặc Biệt', 'Topping: Hải sản tươi ngon, ghẹ, tôm, mực', 95000, 'vietnamese', 'sticky rice,crab,shrimp,squid,seaweed'),
(22, 'Hải Sản Thêm', 'Tôm, mực, Cá Cơm Rim', 30000, 'vietnamese', 'shrimp,squid,dried fish'),
(23, 'Nem Nướng 1 / phần 1 người', 'Có Kèm Bún, 1p có 3 cây Nem cắt đôi', 84000, 'vietnamese', 'grilled pork sausage,rice noodle,vegetable,rice paper'),
(23, 'Nem nướng 2 / phần 2 người', 'Đầy đủ topping 2 phần và Gói Chung', 186000, 'vietnamese', 'grilled pork sausage,rice noodle,vegetable'),
(23, 'Bánh Ướt Thịt Nướng', '', 60000, 'vietnamese', 'rice noodle,grilled pork,fish sauce'),
(23, 'Bánh Thập Cẩm', '', 55000, 'vietnamese', 'rice noodle,shrimp,pork'),
(23, 'Bánh Bèo(6chén)', '', 50000, 'vietnamese', 'rice flour,shrimp,pork fat'),
(24, 'Miến Trộn Ức Gà Bằm', '', 45000, 'vietnamese', 'glass noodle,chicken breast,vegetable'),
(24, 'Cơm Gà Xé Gỏi + Canh Xà Lách Xoong', 'Gà ta xé tay mềm ngọt, cơm vàng dẻo', 69000, 'vietnamese', 'rice,shredded chicken,vegetable,watercress'),
(24, 'Cơm & Dĩa Gỏi Gà (1 người)', 'Gà ta xé trộn gỏi chua ngọt với rau càng cua', 77000, 'vietnamese', 'rice,shredded chicken,banana blossom,vegetable'),
(24, 'Cơm Gà Xé Gỏi + Canh Rong Biển', 'Gà ta xé tay mềm thơm, cơm vàng dẻo ăn kèm', 69000, 'vietnamese', 'rice,shredded chicken,seaweed'),
(24, 'Cơm Gà Đặc Biệt (Gà + Lòng Gà)', 'Đậm vị gà ta đầy đủ lòng gà béo giòn', 73000, 'vietnamese', 'rice,shredded chicken,chicken offal'),

-- MENU QUẬN 5 (ID 25 ĐẾN 34)
(25, 'CƠM THỊT BA ROI XÀO RUỐC', 'Ăn kèm đồ chua dưa leo', 36000, 'vietnamese', 'rice,pork belly,shrimp paste,cucumber'),
(25, 'BÁNH TRÁNG CUỐN', '', 30000, 'snack', 'rice paper,quail egg,dried shrimp,mango'),
(25, 'BÁNH TRÁNG TRỘN', 'Trứng. Ruốc . Sốt bơ. Khô bò đậu phộng xoài rau răm', 30000, 'snack', 'rice paper,quail egg,beef jerky,peanut,mango'),
(25, '3 CUỐN CHẢ GIÒ HẢI SẢN', 'Ăn kèm sốt trộn mayonail', 35000, 'snack', 'spring roll,seafood,mayonnaise'),
(25, 'CƠM TẤM SƯỜN TRỨNG', 'Ăn kèm dưa leo nước mắm', 55000, 'vietnamese', 'rice,pork chop,egg,cucumber'),
(26, 'Bắp bò hấp', '', 129000, 'hotpot', 'beef shank,ginger,onion'),
(26, 'Đuôi bò hấp', '', 179000, 'hotpot', 'beef tail,ginger,herbs'),
(26, 'Óc bò hấp', '', 129000, 'hotpot', 'beef brain,ginger,peppercorn'),
(26, 'Lòng hấp', '', 129000, 'hotpot', 'beef offal,ginger,chili'),
(26, 'Gù Bò Hấp', '', 179000, 'hotpot', 'beef hump,ginger,fish sauce'),
(27, 'Su kem', '', 55000, 'bakery', 'flour,cream,egg,butter'),
(27, 'Bánh kem bắp', '', 320000, 'bakery', 'flour,sweet corn,cream,sugar'),
(27, 'Bánh Phú Sĩ', '', 50000, 'bakery', 'flour,pandan,cream,coconut'),
(27, 'Bông lan 4 vị', '', 75000, 'bakery', 'flour,egg,sugar,butter'),
(27, 'Bông lan cuộn mứt dâu', '', 43000, 'bakery', 'flour,egg,strawberry jam'),
(28, 'BÁNH SẦU RIÊNG MIX 3 VỊ 12CM FULL SẦU TƯƠI RI6', 'Một chiếc bánh, trải nghiệm đủ 3 vị: Vani - Lá dứa - Khoai môn', 185000, 'bakery', 'durian,flour,vanilla,pandan,taro'),
(28, 'BÁNH SẦU RIÊNG CHOCO HẠNH NHÂN 12CM', 'Kết hợp từ socola đắng nhẹ hoà quyện cùng sầu riêng ri6', 175000, 'bakery', 'durian,flour,chocolate,almond'),
(28, 'BÁNH SẦU RIÊNG NGÀN LỚP 12CM SIÊU SẦU', 'Bánh nguyên vị sầu riêng tươi ri 6, không pha sên', 175000, 'bakery', 'durian,flour,cream,butter'),
(28, 'BÁNH SẦU RIÊNG PHÔ MAI THAN TRE 12CM', 'Kết hợp cùng bột than tre tốt cho sức khoẻ, kem cheese foam', 175000, 'bakery', 'durian,flour,charcoal powder,cheese'),
(28, 'BÁNH SẦU RIÊNG NGÀN LỚP 12CM VỊ LÁ DỨA', 'Vỏ bánh được làm từ lá dứa, thơm dịu hoà quyện', 175000, 'bakery', 'durian,flour,pandan,cream'),
(29, 'Ốc Bươu nướng tiêu', 'Cay cay tiêu xanh nước sốt nướng tạo lẻm đặc biệt', 59000, 'seafood', 'apple snail,green pepper,sauce'),
(29, 'Ốc Bưu Sốt Tiêu Đen', '', 59000, 'seafood', 'apple snail,black pepper,garlic'),
(29, 'Ốc Bươu hấp sả', 'Vị thơm sả chanh kết hợp ốc tươi ngon', 59000, 'seafood', 'apple snail,lemongrass,lime'),
(29, 'Ốc Bươu hấp Thái', 'Ốc tươi ngon hấp nước thái chua chua ngọt ngọt', 59000, 'seafood', 'apple snail,lemongrass,chili,tomyum paste'),
(29, 'Tôm càng xanh nướng phô mai khè', '', 149000, 'seafood', 'prawn,cheese,butter'),
(30, 'Cơm Lươn', 'Lươn, trứng cuộn, rong biển, gừng đỏ', 189000, 'japanese', 'rice,eel,egg,seaweed,ginger'),
(30, 'Cơm Tôm Chiên', 'Tôm chiên, trứng cuộn, rong Biển, gừng đỏ', 108000, 'japanese', 'rice,fried shrimp,egg,seaweed'),
(30, 'Cơm bò Hamburger trứng cuộn', 'Cơm bò Hamburger rưới sốt Ham ăn cùng trứng cuộn', 94500, 'japanese', 'rice,beef patty,egg,demi-glace sauce'),
(30, 'Cơm cà ri bò Hamburger', 'Có thêm cà ri Nhật bao mlem', 117000, 'japanese', 'rice,beef patty,japanese curry'),
(30, 'Cơm bò Hamburger phô mai', 'Thêm phô mai mozzarella cho thêm phần mlem', 108000, 'japanese', 'rice,beef patty,mozzarella cheese'),
(31, 'Combo Hàu Hấp Xả 2kg', 'Hàu được hấp chung với xả và chấm với muối tiêu', 99000, 'seafood', 'oyster,lemongrass,pepper salt'),
(31, 'Combo Hàu Sữa hấp xả 1kg', 'Hàu sữa sẽ được hấp với xả, chấm với muối tiêu', 59000, 'seafood', 'oyster,lemongrass,pepper salt'),
(31, 'Trà tắc', '', 20000, 'beverage', 'tea,kumquat,sugar'),
(31, 'Trà ổi', 'Trà ổi đó nha ...là trà ổi đó', 20000, 'beverage', 'tea,guava,sugar'),
(31, 'Nước ngọt', 'Pepsi, coca, 7up', 20000, 'beverage', 'soda'),
(32, 'Tteobokki', 'Mang về tự nấu', 168000, 'korean', 'rice cake,fish cake,gochujang,scallion'),
(32, 'Lẩu Chả Cá', 'Mang về tự nấu', 192000, 'korean', 'fish cake,anchovy broth,radish'),
(32, 'Tteobokki - Lẩu Chả Cá', 'Mang về tự nấu', 348000, 'korean', 'rice cake,fish cake,gochujang,broth'),
(32, 'Mì tương đen- 짜장면', '', 144000, 'korean', 'noodle,chunjang,pork,onion'),
(32, 'Thịt heo chua ngọt Size Mini-찹쌀탕수육미니', '', 216000, 'korean', 'pork,sweet and sour sauce,flour'),
(33, 'Cơm chiên thập cẩm', 'Ruốc nấm, cà rốt xúc xích chay chả nấm chay dưa leo', 28000, 'vegetarian', 'rice,mushroom floss,vegan sausage,carrot'),
(33, 'Bánh Mì Chả Nấm An Lạc', 'Bánh mì nóng zòn kèm pate nấm dinh dưỡng dưa leo', 25000, 'vegetarian', 'bread,mushroom patty,vegan pate,cucumber'),
(33, 'Bánh Mì Chả Cá Chay', 'Bánh mì giòn rụm kết hợp với chả chay chiên giòn', 18000, 'vegetarian', 'bread,vegan fish cake,cucumber,coriander'),
(33, 'Bánh Mì Nấm (Best Seller)', 'Bánh mì + sốt + nấm + cà chua + dưa leo', 20000, 'vegetarian', 'bread,mushroom,tomato,cucumber'),
(33, 'Bánh Mì Xúc Xích Chay (Best Seller)', 'Bánh mì giòn rụm kết hợp với xúc xích chiên giòn', 18000, 'vegetarian', 'bread,vegan sausage,cucumber,chili'),
(34, 'Sương sáo gói sữa béo', 'Kèm sữa béo ăn là ghiền. Ăn giải nhiệt.', 20000, 'dessert', 'grass jelly,milk,sugar'),
(34, 'Tàu hũ tươi Co Vang', 'Vị truyền thống', 20000, 'dessert', 'soybean,water,sugar'),
(34, 'Set 10 tàu hũ tươi Co Vang', '100% sữa đậu nành tươi nhập khẩu, gừng tươi, lá dứa', 200000, 'dessert', 'soybean,ginger,pandan,cane sugar'),
(34, 'Set 5 Tàu hũ tươi Co Vang', 'Sản phẩm giàu canxi, phù hợp ăn chay, người tiểu đường', 100000, 'dessert', 'soybean,ginger,pandan,cane sugar'),
(34, 'Set 20 tàu hũ Covang', 'Vị ngọt vừa ăn, thơm mùi lá dứa.', 400000, 'dessert', 'soybean,pandan,sugar'),

-- MENU QUẬN 10 (ID 35 ĐẾN 44)
(35, 'Nem Nướng Nha Trang Ngon + Trà Tắc', '', 45000, 'vietnamese', 'grilled pork sausage,rice paper,vegetable,tea'),
(35, 'Nem nướng nha trang + trà tắc', '', 39000, 'vietnamese', 'grilled pork sausage,rice paper,tea'),
(35, 'Nem nướng nha trang', '', 39000, 'vietnamese', 'grilled pork sausage,rice paper,vegetable'),
(35, 'Nem nướng nha trang + coca', '', 39000, 'vietnamese', 'grilled pork sausage,rice paper,soda'),
(35, 'Nem Nướng Nha Trang + 15 Cá Viên Chiên + Trà Tắc', '', 62300, 'vietnamese', 'grilled pork sausage,fish ball,tea'),
(36, '1/2 Con Vịt Quay Tỳ Bà Da Giòn', '1/2 con vịt Quay da giòn, 5 cái bánh bao,rau, dưa chua', 209000, 'vietnamese', 'roasted duck,steamed bun,vegetable'),
(36, 'Combo Vịt Quay Tỳ Bà Da Giòn', '1 Con Vịt Quay da Giòn ,10 cái bánh bao, rau, dưa chua', 389000, 'vietnamese', 'roasted duck,steamed bun,vegetable'),
(36, '1 Con Vịt Quay Tỳ Bà Da Giòn', '1 Con Vịt Quay Da Giòn, rau, dưa chua, nước chấm', 369000, 'vietnamese', 'roasted duck,vegetable'),
(36, 'Combo gà quay - sốt thảo dược đậm vị', '1 gà quay, 4 bánh,1 cơm lam, rau chua, dưa leo', 263000, 'vietnamese', 'roasted chicken,bamboo tube rice,herbs'),
(36, 'Combo gà quay - roast chicken combo', '1 Gà quay + 4 bánh + 1 cơm lam, rau chua, dưa leo', 263000, 'vietnamese', 'roasted chicken,bamboo tube rice,cucumber'),
(37, 'Mix 5 Món - Khách Chọn Loại Sốt (Hộp L)', 'Hộp có sẵn cóc (xoài), đu đủ, rau răm & sốt chấm tùy chọn', 115000, 'snack', 'chicken feet,mango,papaya,sauce'),
(37, 'Mix 4 Món - Khách Chọn Loại Sốt (Hộp T)', 'Hộp có sẵn cóc (xoài), đu đủ, rau răm & sốt chấm', 95000, 'snack', 'chicken feet,mango,papaya,sauce'),
(37, 'Mix 3 Món - Khách Chọn Loại Sốt (Hộp N)', 'Hộp có sẵn cóc (xoài), đu đủ, rau răm & sốt chấm', 75000, 'snack', 'chicken feet,mango,papaya,sauce'),
(37, 'Chân Gà Rút Xương Sốt Thái (Lớn 650gr) + Trà Vải/Đào', 'Combo Ưu Đãi', 147000, 'snack', 'boneless chicken feet,thai sauce,tea'),
(37, 'Chân Gà Rút Xương Sả Tắc (Lớn 650gr) + Trà Sữa', 'Combo Ưu Đãi', 149000, 'snack', 'boneless chicken feet,lemongrass,kumquat,milk tea'),
(38, 'Mì trộn tôm thịt bằm phủ trứng', '', 69000, 'noodle', 'noodle,shrimp,minced pork,egg'),
(38, 'Mì trộn bò lúc lắc phủ trứng', '', 69000, 'noodle', 'noodle,beef,egg,sauce'),
(38, 'Mì trộn bò sốt tiêu xanh', 'Bò mềm, sốt vị tiêu xanh hoà quyện', 69000, 'noodle', 'noodle,beef,green pepper,sauce'),
(38, 'Mì trộn heo chiên giòn phủ trứng', '', 69000, 'noodle', 'noodle,fried pork,egg'),
(38, 'Mì trộn bò cháy tỏi', '', 69000, 'noodle', 'noodle,beef,garlic'),
(39, 'TENDER SHARE', '12 Miếng Tender, 2 Khoai Tây Chiên, 2 Pepsi', 98000, 'fastfood', 'chicken tender,french fries,soda'),
(39, 'TENDER PLUS', '6 Miếng Tender, 1 Khoai Tây Chiên, 1 Pepsi', 68000, 'fastfood', 'chicken tender,french fries,soda'),
(39, 'TENDER SOLO', '4 Miếng Tender, 1 Khoai Tây Chiên, 1 Pepsi', 58000, 'fastfood', 'chicken tender,french fries,soda'),
(39, 'TENDER PARTY', '28 Miếng Tender, 4 Khoai Tây Chiên, 4 Pepsi', 228000, 'fastfood', 'chicken tender,french fries,soda'),
(39, 'KHOAI TÂY CHIÊN', '1 Khoai Tây Chiên, 1 Sauce YumI', 20000, 'fastfood', 'potato,oil'),
(40, 'Trà Chanh Tươi Mật Ông', '', 22950, 'beverage', 'tea,lemon,honey'),
(40, 'Hồng Trà', '', 18700, 'beverage', 'black tea,sugar'),
(40, 'Trà Đào Lắc', '', 21250, 'beverage', 'tea,peach,sugar'),
(40, 'Trà Tắc Xí Muội + Mật Ông', '', 22100, 'beverage', 'tea,kumquat,salted plum,honey'),
(40, 'Trà Dâu Lắc', '', 21250, 'beverage', 'tea,strawberry,sugar'),
(41, 'Sò Huyết xào me', 'Nước sốt me đặc biệt quán hoà quện sò', 59000, 'seafood', 'blood cockle,tamarind sauce'),
(41, 'Sò Huyết cháy tỏi Tóp Mỡ', 'Sò tươi kết hợp cháy tỏi tóp mỡ giòn tan', 59000, 'seafood', 'blood cockle,garlic,pork fat'),
(41, 'Sò Huyết nướng mọi/Lacoste', 'Khi ốc nướng mọi giữ nguyên vị tươi ốc', 59000, 'seafood', 'blood cockle'),
(41, 'Nhum biển nướng trứng cút', '', 55000, 'seafood', 'sea urchin,quail egg'),
(41, 'Nhum biển nướng mỡ hành', '', 55000, 'seafood', 'sea urchin,scallion,oil'),
(42, 'Pad Thai Tôm', 'Stir-fried rice-noodle with Shrimps', 68500, 'thai', 'rice noodle,shrimp,egg,peanut'),
(42, 'Pad Thai Bò', 'Thịt bò, hũ tiếu, giá, hẹ, chanh ớt đậu phộng', 75000, 'thai', 'rice noodle,beef,bean sprout,peanut'),
(42, 'Hủ tiếu áp chảo với Tôm', 'Hủ tiếu, tôm, trứng, rau cải', 68500, 'thai', 'rice noodle,shrimp,egg'),
(42, 'Pad Thai Gà', 'Stir-fried rice-noodle with Chicken', 68500, 'thai', 'rice noodle,chicken,egg,peanut'),
(42, 'Hủ tiếu mềm xào thịt Bò', 'Thịt bò, hũ tiếu, rau cải', 75000, 'thai', 'rice noodle,beef,vegetable'),
(43, 'Mì tương đen- 짜장면', '', 120000, 'korean', 'noodle,chunjang,pork,onion'),
(43, 'Thịt heo chua ngọt Size Mini', '', 180000, 'korean', 'pork,sweet and sour sauce'),
(43, 'Há cảo chiên-군만두', '', 100000, 'korean', 'flour,pork,vegetable'),
(43, 'Mỳ lạnh nước', '', 140000, 'korean', 'cold noodle,broth,egg,cucumber'),
(43, 'Mỳ lạnh trộn', '', 140000, 'korean', 'cold noodle,gochujang,egg,cucumber'),
(44, 'Số 1', 'Bò, Trứng, Pate', 59000, 'vietnamese', 'beef,egg,pate,bread'),
(44, 'Số 2', 'Nhiều bò, trứng', 70000, 'vietnamese', 'beef,egg,bread'),
(44, 'Bò né đặc biệt', 'Bò, Trứng, Pate, Xúc xích, Chả, Nem nướng,thịt nguội, phô mai cục', 91000, 'vietnamese', 'beef,egg,pate,sausage,cheese'),
(44, 'Số 3', 'Bò, Trứng, Pate, Xúc xích, chả', 69000, 'vietnamese', 'beef,egg,pate,sausage'),
(44, 'Số 4', 'Bò, Trứng, Pate, Xúc xích, Chả, Nem, thịt nguội', 75000, 'vietnamese', 'beef,egg,pate,sausage,pork roll'),

-- MENU QUẬN 11 (ID 45 ĐẾN 64)
(45, 'Set B - Cơm Cá hồi Nauy, Trứng Ngâm tương', '45gr Cá + 1 Trứng + Đồ ăn kèm', 139500, 'japanese', 'salmon,egg,rice,kimchi,seaweed'),
(45, 'Set A - Cơm Cá hồi Nauy Ngâm tương', '45gr Cá + Đồ ăn kèm', 114300, 'japanese', 'salmon,rice,kimchi,seaweed'),
(45, 'Set C - Cơm Cá hồi Nauy, Tôm Ngâm tương', '45gr Cá + 3 Tôm + Đồ ăn kèm', 157500, 'japanese', 'salmon,shrimp,rice,seaweed'),
(45, 'Cá Hồi Nauy Ngâm Tương (Riêng)', '100gr Cá hồi + Sốt ngâm', 215100, 'japanese', 'salmon,soy sauce,ginger'),
(45, 'Tôm Thẻ Ngâm Tương (Riêng)', '10 con Tôm + Sốt ngâm', 161100, 'japanese', 'shrimp,soy sauce,garlic'),
(46, 'Phở Tái', '', 55000, 'vietnamese', 'rice noodle,beef,beef broth,herbs'),
(46, 'Phở Nạm', '', 55000, 'vietnamese', 'rice noodle,beef flank,beef broth'),
(46, 'Phở Gân', '', 55000, 'vietnamese', 'rice noodle,beef tendon,beef broth'),
(46, 'Phở Viên', '', 55000, 'vietnamese', 'rice noodle,beef ball,beef broth'),
(46, 'Phở Đặc Biệt', '', 75000, 'vietnamese', 'rice noodle,beef,tendon,beef ball'),
(47, 'Bánh Mì Chảo Đặc Biệt', '2 trứng, xúc xích, pate, cá mòi', 55000, 'vietnamese', 'egg,sausage,pate,sardine,bread'),
(47, 'Bánh Mì Chảo Thường', '2 trứng, pate, chả', 35000, 'vietnamese', 'egg,pate,pork roll,bread'),
(47, 'Bò Bít Tết Khoai Tây', '', 65000, 'vietnamese', 'beef,potato,bread,salad'),
(47, 'Bò Bít Tết Trứng Ốp La', '', 65000, 'vietnamese', 'beef,egg,bread,salad'),
(47, 'Bánh Mì Thịt Nướng', '', 25000, 'vietnamese', 'bread,grilled pork,cucumber'),
(48, 'Cơm Bò Beefsteak Phủ Trứng', '', 65000, 'vietnamese', 'rice,beef,egg,onion'),
(48, 'Cơm Tôm Rim Mặn Phủ Trứng', '', 55000, 'vietnamese', 'rice,shrimp,egg,fish sauce'),
(48, 'Mì Ý Bò Bằm Phủ Trứng', '', 55000, 'vietnamese', 'pasta,beef,tomato sauce,egg'),
(48, 'Nui Xào Bò Phủ Trứng', '', 55000, 'vietnamese', 'macaroni,beef,egg,vegetable'),
(48, 'Canh Rong Biển Thịt Bằm', '', 15000, 'vietnamese', 'seaweed,minced pork,ginger'),
(49, 'Hủ Tiếu Chay Thập Cẩm', '', 35000, 'vegetarian', 'rice noodle,tofu,mushroom,vegetable'),
(49, 'Hủ Tiếu Nam Vang Chay', '', 35000, 'vegetarian', 'rice noodle,tofu,mushroom,carrot'),
(49, 'Mì Vàng Chay', '', 35000, 'vegetarian', 'egg noodle,tofu,mushroom,vegetable'),
(49, 'Bún Huế Chay', '', 35000, 'vegetarian', 'rice noodle,tofu,lemongrass,chili'),
(49, 'Gỏi Cuốn Chay', '', 21000, 'vegetarian', 'rice paper,tofu,vermicelli,herbs'),
(50, 'Cơm Gà Hải Nam', '', 75000, 'chinese', 'rice,chicken,ginger sauce'),
(50, 'Cơm Xá Xíu', '', 65000, 'chinese', 'rice,bbq pork,soy sauce'),
(50, 'Cơm Heo Quay', '', 65000, 'chinese', 'rice,roasted pork,soy sauce'),
(50, 'Canh Cải Chua Sườn Non', '', 45000, 'chinese', 'mustard green,pork rib'),
(50, 'Đậu Hủ Ma Bà', '', 55000, 'chinese', 'tofu,minced pork,chili paste'),
(51, 'Sủi Cảo Thập Cẩm', 'Sủi cảo, mực, cá viên, tôm', 70000, 'chinese', 'dumpling,shrimp,squid,fish ball'),
(51, 'Sủi Cảo Không', '', 60000, 'chinese', 'shrimp dumpling,pork broth'),
(51, 'Mì Sủi Cảo', '', 70000, 'chinese', 'egg noodle,shrimp dumpling'),
(51, 'Sủi Cảo Chiên', '', 70000, 'chinese', 'shrimp dumpling,oil,sauce'),
(51, 'Hủ Tiếu Sủi Cảo', '', 70000, 'chinese', 'rice noodle,shrimp dumpling'),
(52, 'Sủi Cảo Tôm Mực', '', 70000, 'chinese', 'shrimp dumpling,squid,pork broth'),
(52, 'Mì Sủi Cảo Thập Cẩm', '', 75000, 'chinese', 'egg noodle,shrimp dumpling,fish ball'),
(52, 'Sủi Cảo Chiên Giòn', '', 70000, 'chinese', 'shrimp dumpling,oil'),
(52, 'Súp Sủi Cảo Viên', '', 70000, 'chinese', 'shrimp dumpling,fish ball,broth'),
(52, 'Xá Xíu Đĩa', '', 100000, 'chinese', 'bbq pork,soy sauce,honey'),
(53, 'Sủi Cảo Nước', '', 65000, 'chinese', 'shrimp dumpling,pork broth,vegetable'),
(53, 'Mì Sủi Cảo Xá Xíu', '', 70000, 'chinese', 'egg noodle,shrimp dumpling,bbq pork'),
(53, 'Sủi Cảo Thập Cẩm Đặc Biệt', '', 80000, 'chinese', 'shrimp dumpling,squid,pork,fish ball'),
(53, 'Hoành Thánh Nước', '', 55000, 'chinese', 'wonton,pork,broth'),
(53, 'Sủi Cảo Chiên Phần', '', 70000, 'chinese', 'shrimp dumpling,oil'),
(54, 'Sủi Cảo Tôm Tươi', '', 65000, 'chinese', 'shrimp dumpling,pork broth'),
(54, 'Mì Sủi Cảo Thập Cẩm', '', 75000, 'chinese', 'egg noodle,shrimp dumpling,squid'),
(54, 'Sủi Cảo Chiên', '', 70000, 'chinese', 'shrimp dumpling,flour,oil'),
(54, 'Hủ Tiếu Mì Sủi Cảo', '', 75000, 'chinese', 'rice noodle,egg noodle,dumpling'),
(54, 'Đĩa Mực Thêm', '', 50000, 'chinese', 'squid,pork broth'),
(55, 'Số 1 - Bò Trứng Pate', '', 59000, 'vietnamese', 'beef,egg,pate,bread'),
(55, 'Số 2 - Nhiều Bò Trứng', '', 70000, 'vietnamese', 'beef,egg,bread'),
(55, 'Bò né đặc biệt', 'Bò, Trứng, Pate, Xúc xích, Chả', 91000, 'vietnamese', 'beef,egg,pate,sausage,cheese'),
(55, 'Số 3 - Bò Xúc Xích', '', 69000, 'vietnamese', 'beef,egg,pate,sausage'),
(55, 'Khoai tây chiên', '', 28000, 'vietnamese', 'potato,oil'),
(56, 'Sương sáo gói sữa béo', '', 20000, 'dessert', 'grass jelly,milk,sugar'),
(56, 'Tàu hũ tươi Co Vang', '', 20000, 'dessert', 'soybean,water,sugar'),
(56, 'Set 5 Tàu hũ tươi', '', 100000, 'dessert', 'soybean,ginger,pandan'),
(56, 'Sữa chua vị truyền thống', '', 16000, 'dessert', 'milk,yogurt culture'),
(56, 'Panna cotta chanh dây', '', 17000, 'dessert', 'milk,cream,passion fruit'),
(57, 'Bánh ướt đặc biệt', '', 65000, 'vietnamese', 'rice noodle,pork sausage,herbs'),
(57, 'Bánh cuốn trứng lá dứa', '', 65000, 'vietnamese', 'rice noodle,egg,pandan'),
(57, 'Bánh dày kẹp chả', '', 20000, 'vietnamese', 'sticky rice,pork sausage'),
(57, 'Bánh Giò', '', 20000, 'vietnamese', 'rice flour,minced pork,mushroom'),
(57, 'Bánh tôm chiên', '', 13000, 'vietnamese', 'shrimp,flour,oil'),
(58, 'Bánh mix 3 vị 12cm', '', 185000, 'bakery', 'durian,flour,vanilla,pandan,taro'),
(58, 'Bánh choco hạnh nhân 12cm', '', 175000, 'bakery', 'durian,flour,chocolate,almond'),
(58, 'Bánh ngàn lớp truyền thống', '', 175000, 'bakery', 'durian,flour,cream,butter'),
(58, 'Bánh phô mai than tre', '', 175000, 'bakery', 'durian,flour,charcoal,cheese'),
(58, 'Bánh ngàn lớp lá dứa', '', 175000, 'bakery', 'durian,flour,pandan,cream'),
(59, 'Chân Gà Chiên Rút Xương', '', 90000, 'snack', 'chicken feet,cucumber,chili salt'),
(59, 'Khoai Tây Lắc Phô Mai', '', 38000, 'snack', 'potato,cheese'),
(59, 'Mẹt Chiên size S', '', 53000, 'snack', 'fish ball,beef ball,sausage'),
(59, 'Gà Viên Lắc Phô Mai', '', 38000, 'snack', 'chicken,cheese,flour'),
(59, 'Gân Bò Xào', '', 105000, 'snack', 'beef tendon,cucumber,herbs'),
(60, 'Pad Thái Tôm', '', 119000, 'thai', 'rice noodle,shrimp,egg,peanut'),
(60, 'Mì TomYum Thai', '', 99000, 'thai', 'noodle,shrimp,lemongrass,chili'),
(60, 'Cà Ri Gà Thái', '', 89000, 'thai', 'chicken,coconut milk,curry paste'),
(60, 'Xôi Xoài Thái', '', 65000, 'thai', 'sticky rice,mango,coconut milk'),
(60, 'Trà Sữa Thái Đỏ', '', 35000, 'thai', 'thai tea,milk,sugar'),
(61, 'Combo No Nê', '1 Mì Trộn Cá Viên + 1 Nước', 50000, 'snack', 'noodle,fish ball,soda'),
(61, 'Xúc Xích Lốc Xoáy', '', 30000, 'snack', 'sausage,flour,oil'),
(61, 'Mì Trộn Full Topping', '', 60000, 'snack', 'noodle,fish ball,beef ball,sausage'),
(61, 'Tôm hùm viên', '', 25000, 'snack', 'lobster ball,oil'),
(61, 'Mì Trộn Mandu', '', 45000, 'snack', 'noodle,dumpling,sauce'),
(62, 'Tender Plus', '6 miếng gà + khoai + pepsi', 68000, 'fastfood', 'chicken tender,potato,soda'),
(62, 'Tender Solo', '4 miếng gà + khoai + pepsi', 58000, 'fastfood', 'chicken tender,potato,soda'),
(62, 'Tender 10 PCS', '', 88000, 'fastfood', 'chicken tender,sauce'),
(62, 'Khoai Tây Chiên', '', 20000, 'fastfood', 'potato,oil,salt'),
(62, 'Jumbo Big', '30 miếng gà + sốt', 208000, 'fastfood', 'chicken tender,sauce'),
(63, 'Mì trộn tôm thịt bằm', '', 69000, 'noodle', 'noodle,shrimp,minced pork,egg'),
(63, 'Mì trộn bò lúc lắc', '', 69000, 'noodle', 'noodle,beef,egg,sauce'),
(63, 'Cơm bò cháy tỏi', '', 69000, 'noodle', 'rice,beef,garlic,egg'),
(63, 'Canh rong biển thịt bằm', '', 25000, 'noodle', 'seaweed,minced pork'),
(63, 'Trà tắc xí muội', '', 25000, 'noodle', 'tea,kumquat,salted plum'),
(64, 'Cơm chiên thập cẩm', '', 28000, 'vegetarian', 'rice,vegan sausage,carrot,tofu'),
(64, 'Bánh mì chả nấm', '', 25000, 'vegetarian', 'bread,mushroom patty,pate'),
(64, 'Bánh mì xíu mại chay', '', 20000, 'vegetarian', 'bread,vegan meatball,sauce'),
(64, 'Mì trộn chay', '', 35000, 'vegetarian', 'noodle,vegan beef ball,egg,vegetable'),
(64, 'Combo Sinh Viên', 'Bánh mì + Nước', 32000, 'vegetarian', 'bread,vegan topping,soda');